# Tensors
Tensors는 배열과 행렬과 비슷한 특수한 자료구조이다. Pytorch에서 모델의 input과 output 그리고 모댈의 매개변수를 위해 사용한다. 
Tensors는 Numpy의 ndarrays와 비슷하다. 텐서는 GPU 또는 다른 하드웨어 가속장치를 이용할 수 있다. 텐서와 넘파이 배열은 같은메모리를 공유할 수 있고, 데이터 복사를 줄일 수 있다. 

In [2]:
import torch 
import numpy as np

In [3]:
# Tensor initializing
# 데이터로 부터 바로 만들 수 있다. 
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [5]:
# Numpy 배열에서 Tensors로 생성가능
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
# 다른 텐서에서 부터 특성을 유지하여 새로운 텐서 생성
x_ones = torch.ones_like(x_data)    #  torch.ones_like(x_data) --> 스칼라 값 1로 채워서 보낸다  
print(f"Ones Tensor: \n {x_ones} \n")

x_rand= torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7603, 0.9738],
        [0.7734, 0.3446]]) 



In [9]:
# 텐서의 차원을 튜플로 나타낸다

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7288, 0.4250, 0.0077],
        [0.1688, 0.2043, 0.4104]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# 텐서 속성 
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서의 연산자

In [12]:
# 텐서가 GPU로 이동 가능한 경우 이동
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [14]:
# indexing과 slicing은 numpy와 비슷하다
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# tensors joining
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
# 산술 연산

# 두 tensor의 곱셈
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [18]:
# 각 행렬의 원소 끼리만 곱하기 (element wise product / hadmamard product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [20]:
# 하나의 원소인 tensor
agg = tensor.sum()
agg_item = agg.item()   # item()을 통해 숫자의 변수 타입을 문자열로 나타냄
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [21]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#  Numpy와 연동

In [22]:
# tensor에서 numpy array로 

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
# 텐서의 변동은 Numpy 배열에도 영향을 준다 
t.add(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [24]:
# Numpy 배열에서 Tensor로

n = np.ones(5)
t= torch.from_numpy(n)

In [26]:
# Numpy의 변동은 텐서에도 영향이 있다

np.add(n, 1, out= n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
